### ISSUE TITLE
ImportError: cannot import name ChainMap

### ISSUE THREAD

**Issue by swathimithran** [jjangsangy/ExplainToMe#9]
Hi Sir,

I tried installing the project according to the readme steps, But i am getting ImportError when I run the command "python manage.py runserver", I tried using docker installation but I am getting the same ImportError, the stack trace is as given below:

ExplainToMe$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    app = create_app()
  File "/home/swathimithran/ExplainToMe/ExplainToMe/app.py", line 46, in create_app
    f(app)
  File "/home/swathimithran/ExplainToMe/ExplainToMe/app.py", line 27, in register_blueprints
    from . views import root, api
  File "/home/swathimithran/ExplainToMe/ExplainToMe/views/__init__.py", line 2, in <module>
    from . root import root
  File "/home/swathimithran/ExplainToMe/ExplainToMe/views/root.py", line 4, in <module>
    from collections import ChainMap
ImportError: cannot import name ChainMap

**Comment by jjangsangy** [comment]
Thanks for reporting this, I've recently ported the code to Python 3 by default and Chainmap was moved out of stdlib in Python 3. I'll patch this issue, but if you want to run this on Python 2, you need to install Chainmap using.

    pip install chainmap

And wrap the code that imports chainmap in a try..except

    try:
         from collections import ChainMap
    except ImportError:
         from chainmap import ChainMap

**Comment by jjangsangy** [comment]
https://github.com/jjangsangy/ExplainToMe/commit/4758d02baa685440084bb3d3b050c35ecce5123c: The fix has been implemented and it's live.
